### ISSUE TITLE
Error when inserting images

### ISSUE THREAD

**Issue by SalunMarvin** [bpampuch/pdfmake#1085]
Hi, guys!
I'm having some problem to add images to the PDF. It's a Node application (an API with pipe-server) that saves locally the PDF.

When I try to put the PATH to the image, the following error is given:
_invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)_

And when I try to put the Base64 converted image (by this site: https://www.base64-image.de/) I get this error:

_Error: unsupported number: NaN_

I can't evolve the application, it doesn't work anyway. I tried, inclusive, putting the same base 64 image from the playground and got this error.

This is the saving file code:

  pdfDocument.pipe(fs.createWriteStream('pdfs/output2.pdf'))

  pdfDocument.end()

**Comment by liborm85** [comment]
Attach full example source code for reproduce problem.

**Comment by SalunMarvin** [comment]
@liborm85 sorry, didn't received any notification of this answer, here you have the code:

`let PDFDocument = require('pdfmake')
let fs = require('fs')
let path = require('path');

exports.exportPDF = function* (request, reply) {
  let fonts = {
    Roboto: {
      normal: './fonts/Roboto-Regular.ttf',
      bold: './fonts/Roboto-Medium.ttf',
      italics: './fonts/Roboto-Italic.ttf',
      bolditalics: './fonts/Roboto-MediumItalic.ttf'
    }
  }

  let document = new PDFDocument(fonts)

  let docDefinition = {
    content: [
      {
        columns: [{
          width: 'auto',
          image: './images/knowhowlogo.png'
        },
        [{
          width: '*',
          text: 'TEST',
          fontSize: 16
        },
        { text: 'TEST', fontSize: 8 },]
        ],
        columnGap: 10
      },
    ],
    styles: {
      content: {
        fontSize: 10,
        bold: false
      },
      signature: {
        fontSize: 12,
        bold: false
      }
    },
  }

  let pdfDocument = document.createPdfKitDocument(docDefinition)

  pdfDocument.pipe(fs.createWriteStream('pdfs/output.pdf'))

  pdfDocument.end()

  let APIResponse = {
    'PDF': 'pdfs/output.pdf'
  }

  reply(
    APIResponse
  )
}`

**Comment by 7samurai** [comment]
I think its the problem, when you try colums with images and width. When you habe an image and width, the width is used for the image, and there ist no string width. I ran into the same problem. Try for testing an Number for the width at the image part: 
... columns: [{
width: 100,
image: './images/knowhowlogo.png'
} 
.....

**Comment by ocastx** [comment]
I have the same problem. Checked the code and found the root cause where NaN is generated: 

In the `src/docMeasure.js` the function `measureImage` function tries to calculate the size of the image by the given sizes of the image. But both the `node.width` and `imageSize.width` is defined as "20%". The code doesn't check for any width strings and tries to calculate the width size value in the following lines which generates the NaN and throws an error in the PDFKit library

`if (node.fit) {
		var factor = (imageSize.width / imageSize.height > node.fit[0] / node.fit[1]) ? node.fit[0] / imageSize.width : node.fit[1] / imageSize.height;
		node._width = node._minWidth = node._maxWidth = imageSize.width * factor;
		node._height = imageSize.height * factor;
	} else {
		node._width = node._minWidth = node._maxWidth = node.width || imageSize.width;
		node._height = node.height || (imageSize.height * node._width / imageSize.width);

		if (typeof node.maxWidth === "number" && node.maxWidth < node._width) {
			node._width = node._minWidth = node._maxWidth = node.maxWidth;
			node._height = node._width * imageSize.height / imageSize.width;
		}

		if (typeof node.maxHeight === "number" && node.maxHeight < node._height) {
			node._height = node.maxHeight;
			node._width = node._minWidth = node._maxWidth = node._height * imageSize.width / imageSize.height;
		}

		if (typeof node.minWidth === "number" && node.minWidth > node._width) {
			node._width = node._minWidth = node._maxWidth = node.minWidth;
			node._height = node._width * imageSize.height / imageSize.width;
		}

		if (typeof node.minHeight === "number" && node.minHeight > node._height) {
			node._height = node.minHeight;
			node._width = node._minWidth = node._maxWidth = node._height * imageSize.width / imageSize.height;
		}
	}`

As there is no available width given in the function it is actually not possible to calculate the correct percentage of the available width. It has to be preprocessed.

I didn't have time to find the right part of the code where preprocessing of the width values happen except for the lines in `columnCalculator.js` where the percentage values are converted to numbers in line 27.

**Comment by chalangr12** [comment]
you can't reference the files using the file path, you have to convert them to base64. See Below
```
{
    image: 'data:image/png;base64,' + require('fs').readFileSync(path.resolve(__dirname,'images','logo.png')).toString('base64'),
    height: 100,
    width: 100
}
```
apologies for the crappy styling if it is not up to github community standards, first comment here.

**Comment by ishulev** [comment]
@chalangr12 
Just using `image: path.resolve(__dirname,'images','logo.png')` should suffice :)

**Comment by Lietsaki** [comment]
@7samurai Solved it for me. Incredible that this gotcha is not documented.

**Comment by DylanDile** [comment]
I managed to add image to the pdf using VUS js.
Convert the image to base64 first before rendering it to the pdf. 
Pass your image path the getBase64ImageFromUrl function

{
      /*image: await this.getBase64ImageFromURL(
          "https://images.pexels.com/photos/209640/pexels-photo-209640.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=300"
      ),*/

      image: await this.getBase64ImageFromURL(
          "/images/books.jpg"
      ),
      fit: [100, 100],
      //pageBreak: 'after'
  },

getBase64ImageFromURL(url) {
      return new Promise((resolve, reject) => {
          var img = new Image();
          img.setAttribute("crossOrigin", "anonymous");

          img.onload = () => {
              var canvas = document.createElement("canvas");
              canvas.width = img.width;
              canvas.height = img.height;

              var ctx = canvas.getContext("2d");
              ctx.drawImage(img, 0, 0);

              var dataURL = canvas.toDataURL("image/png");

              resolve(dataURL);
          };

          img.onerror = error => {
              reject(error);
          };

          img.src = url;
      }

**Comment by jdempcy** [comment]
You can insert them locally if you put them in ./examples/fonts from the pdfmake root. Then the URL will be "./___filename___.jpg" (or .png).

**Comment by Cyberistic** [comment]
> You can insert them locally if you put them in ./examples/fonts from the pdfmake root. Then the URL will be "./_**filename**_.jpg" (or .png).

Thank you! This worked for me (though it should be "filename.jpg" without "./")

turns out, it's buried in the docs: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/
> The above steps embeds all files from examples/fonts (into a local key/value variable pdfMake.vfs) - not only fonts. Which means you could put images in there, run node build-vfs.js "./examples/fonts, and reference them by filename in your doc-definition object.

Full steps (In case docs are gone):

1. create a new vfs_fonts.js containing your font files 
- Install pdfmake npm install pdfmake
- Go to package directory ./node_modules/pdfmake/
- Create the examples/fonts subdirectory in your pdfmake code directory, if it doesn’t already exist.
- Copy your images/fonts (and other files you wish to embed) into the examples/fonts subdirectory.
- Run command node build-vfs.js "./examples/fonts". Or run node build-vfs.js to show help.
- Include your new build/vfs_fonts.js file in your code (in the same way you include pdfmake.js or pdfmake.min.js).

2. Set images
pdfMake.Images = {
yourimagename: "filename.jpg"
}

3. You can now reference your image
      {
        image: "yourimagename",
        width: 100,
        height: 100,
        absolutePosition: { x: 400, y: 550 },
      },
