### ISSUE TITLE
Creating pdf consume high memory

### ISSUE THREAD

**Issue by soohan92** [bpampuch/pdfmake#1208]
I am generating 3 tables in my pdf as below:
Table 1  - 2 columns 6 rows
Table 2 - 10 columns 200,000 rows
Table 3 - 2 columns 6 rows

File size - 80MB
Pages - 16,000 pages
Time to generate PDF - 40 minutes
--max-old-space-size = 40000 (MB)

I need to assign 40Gb of memory to generate this PDF and it tooks a long time to generate which is unacceptable. Any way to enhance my current situation?

**Comment by Wabbala** [comment]
😨 why would you do that in the first place? Who is going through a pdf of 200k+ rows? Isn't it better to export that to a csv/excel/etc. ?

**Comment by liborm85** [comment]
Problem is in pdfkit - https://github.com/devongovett/pdfkit/issues/728

duplicate: https://github.com/bpampuch/pdfmake/issues/1052

**Comment by soohan92** [comment]
Thread closed but any solution ?

**Comment by liborm85** [comment]
**DUPLICATE**

**Comment by Wabbala** [comment]
@soohan92, it may be a requirement, but what is the use of this requirement you may also wonder! Think in usability instead of just following requirements. Dare to question it! You can't do anything with a pdf which contains more than 20k rows. No analysis can be conducted, storage of it is sh*t. So first get the use case. Solve the cause of the problem then the problem itself 😉
