### ISSUE TITLE
It's possible use .open() and .print() without disable adBlock?

### ISSUE THREAD

**Issue by AlisonVilela** [bpampuch/pdfmake#1210]
`.open()` or `.print()` not work with adBlock, `.download()` works fine.
But, all my users need disable adBlock, this is inconvenient, we have any other solution for this?

**Comment by liborm85** [comment]
No, see issue: https://github.com/bpampuch/pdfmake/issues/800. I do not know how to bypass blocking in AdBlock.

**Comment by FrancescoMussi** [comment]
Damn adBlock!
Because of this I am thinking of scrapping the `print()` and use the `download()` instead.
But it is actually a pity!
Using the print dialog I believe is much more user-friendly.
And I would prefer to avoid asking to disable adBlock.

There is no hope of overcoming this?
Great library btw!
