### ISSUE TITLE
New nice documentation

### ISSUE THREAD

**Issue by liborm85** [bpampuch/pdfmake#1238]
### New documentation: https://pdfmake.github.io/docs/

Sources is available here: https://github.com/pdfmake/docs

Help with improvement documentation is welcome.

---

Create a nice and clear new documentation.

Now all documentation is in [readme file](https://github.com/bpampuch/pdfmake/blob/master/README.md) and [Wiki](https://github.com/bpampuch/pdfmake/wiki).
On pdfmake.org site is in [Getting started (docs) tab](http://pdfmake.org/#/gettingstarted) old and not updated documentation, which is confusing for visitors.

Text on http://pdfmake.org/#/gettingstarted is hard to maintain because it is one long html file. It would be great documentation to write in Markdown and convert to html automatically, it can [Hugo framework](https://gohugo.io/) with theme for creating docs (eg. https://themes.gohugo.io/material-docs/).
I do not know whether it's possible to "connect" Hugo docs page with the classic website. Thought as keep [homepage](http://pdfmake.org/), [tab Features](http://pdfmake.org/index.html#/features) and [tab Playground](http://pdfmake.org/playground.html) pages (or with minor modifications for compatibility with Hugo) and "only" change [Getting started (docs) tab](http://pdfmake.org/#/gettingstarted) from html to Hugo.

And then we could be able to write a nice documentation on pdfmake.org and remove it from [readme file](https://github.com/bpampuch/pdfmake/blob/master/README.md).

**Comment by JiaXueYan** [comment]
Can you change zhe table border color ? I need some idea

**Comment by jfdesrochers** [comment]
It might not be a 'nice documentation' or even a replacement of the readme.md, but I've compiled everything I could find in the examples, in the playground and in the readme into a 'Cheat Sheet'. That way it make it easier to remember which properties go in which tag, etc. Anyone interested can find it here: https://gist.github.com/jfdesrochers/08833957232a04638c1cad4d071b31e9

It needs to be noted that this is meant for someone who already understands how to use PDFMake and is to be used as a reference (instead of combing through the examples every time).

**Comment by piisawheel** [comment]
Hi! Your shiny new documentation is old again.  Specifically I could not get *any* of the methods to work except open('', '_blank').
I was able to figure out the problem...
I could not use any pdfmake functions that had promises involved, using the documented syntax.
Things like getBase64(callback) needs to become getBase64().then(callback).  getDataUrl.then(callback) etc.  These are the only 2 I tested because after I figured it out (they all failed) on getBase64, I moved onto getDataUrl which solved my issue (getting my pdf into an iframe).

I spent like 4 hours only to figure out I was missing that stupid .then().

I hope this helps others.

Affected Methods (Afaict) are:
getDataUrl
getBase64
getBuffer
getBlob
getStream

**Comment by liborm85** [comment]
If you are newbie, why do you use unstable master version? Try to read warning in readme in master: [readme](https://github.com/bpampuch/pdfmake/blob/master/README.md#this-is-unstable-master-branch-for-version-02x-for-stable-version-01x-see-branch-01)
And use latest stable version from [npm](https://www.npmjs.com/package/pdfmake) or other [sources](https://pdfmake.github.io/docs/getting-started/).

**Comment by piisawheel** [comment]
I am *not* a newbie. I needed the features.  The fact that I was missing .then for my promises is an easy syntax error to make.  Or are you a perfect coder who's *never* spent time only to realize you were making a stupid mistake?
And typically, when i'm trying to solve a problem, I turn first to the documentation.  
Your version 1 *AND* version 2 branch readme files *both point to the same documentation!*
If the documentation is *wrong,* or wrong for 1 or the other branch, how the hell am I supposed to know? Cause *your documentation doesn't have any version numbers on it.*
So, you have 1 set of documentation for 2 versions with no version information on it that are apparently different being pointed to from 2 different branches that tells people to do the wrong thing, and you wonder why they get frustrated and have to *dig* into *your* code only to realize they were making a simple mistake, because they were following your documentation a _little_ too closely.

No dude, i'm not a newbie.  This one's on you!

**Comment by liborm85** [comment]
If you really read the documentation, follow its text! In documentation [here](https://pdfmake.github.io/docs/getting-started/client-side/) is described how to install/download pdfmake. It is not written anywhere that you have to use a master branch.

The documentation for version 0.2 does not exist because this version is still under development and there is no tag and not released.

In readme is a warning:
> #### This is unstable master branch for version 0.2.x, for stable version 0.1.x see [branch 0.1](https://github.com/bpampuch/pdfmake/tree/0.1).

Each library has some work in progress that has not yet been completed. Therefore, it is not possible to blindly just clone a git and expect everything to work properly, according to documentation of another version.

If you are not newbie, then you already use pdfmake somewhere and you should use the stable version in production... if not, good luck dude.

**Comment by piisawheel** [comment]
Sure.  Can you fix the readme for Version 2 so it doesn't point to version 1's documentation then?  Cause that's confusing as hell.
