### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by jerroldseet** [bpampuch/pdfmake#1240]
I've trying to generate a PDF and I have some error after download immediate after I finish generate the PDF files. This error says that it Failed to load PDF document.

I want the file to be download immediately after I generate the pdf file

`var docDefinition = {
    content: 'test',
  }; 
  var pdfDoc = printer.createPdfKitDocument(docDefinition);
  pdfDoc.pipe(fs.createWriteStream('name.pdf'));
  pdfDoc.end();
  res.download('name.pdf');`

**Comment by liborm85** [comment]
I don'tt know what's in variable `res`, bude in server side is not supported download because is not available browser.

Here is example how to save pdf file in server side: https://github.com/bpampuch/pdfmake/blob/master/examples/basics.js

If you want user download method, you need use client side version in browser, see example:
https://github.com/bpampuch/pdfmake#download-the-pdf

**Comment by jerroldseet** [comment]
I am using Nodejs btw

**Comment by liborm85** [comment]
Then first example of usage.
