### ISSUE TITLE
How to know the height of the header

### ISSUE THREAD

**Issue by MathLavallee** [bpampuch/pdfmake#1322]
I created a pdf that the header height is dynamic and I want to put the margin of the content page according to that header height. Is there a way to get the header height that is created ? The header will change according to the information that the user will put. So I can't predict how much the height will be.

If you have any question, don't be shy to ask.

Thank you.

**Comment by dudusotero** [comment]
The height of the header is the same as the top margin of the page, so I believe that changing the margin value would already solve your problem regarding the dynamic height of the header.

**Comment by Dragomir-Ivanov** [comment]
@dudusotero I believe that @MathLavallee wanted to say, that he has dynamic content that is printed on the header, like different number of text rows, etc. So he can't put fixed value in the `pageMargins` because if text is too large it will be truncated. 
I have the same issue, is any way to know the height of any rendered `pdf` document. I am ready to pre-render the header alone, get its height, then create the whole document with `pageMargins` calculated from the pre-rendered header.

Thanks.

PS: @MathLavallee how did you resolved this issue?

**Comment by edwin177** [comment]
I would love pageMargins to accept a function, like header and footer, so I can change margins per page.
