### ISSUE TITLE
(node:84) [DEP0005] DeprecationWarning: Buffer() is deprecatede

### ISSUE THREAD

**Issue by saostad** [bpampuch/pdfmake#1472]
Hi,
When I creating PDF file I am getting warning below:

> (node:184) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

I test it with node version 10.3.0 and 10.9.0 but nothing changed.

**Comment by liborm85** [comment]
I tried run basic example ([/examples/basics.js](https://github.com/bpampuch/pdfmake/blob/master/examples/basics.js)) on node 10.9.0 by command `node basics.js` and passed without any warning.

How can I simulate it?

**Comment by liborm85** [comment]
No reaction, non-reproducible.

**Comment by bmoquist** [comment]
I encountered this while setting up fonts on the server a while back from referencing commentary in the Github issues. #1312 has a line using the deprecated Buffer() and should be changed to Buffer.from() if accessing Roboto from the virtual file system instead of a ttf on the server. The better option though is just to download the actual ttf file to reference directly. 

``` js
const robotoRegular = require('pdfmake/build/vfs_fonts.js').pdfMake.vfs['Roboto-Regular.ttf']

const fonts = {
    Times: {
      normal: './assets/fonts/Times.ttf'
    },
    Roboto: {
      normal: new Buffer.from(robotoRegular, 'base64'),
    }
  }
```
