### ISSUE TITLE
how can i make it works with hebrew and arabic language

### ISSUE THREAD

**Issue by basherodeh** [bpampuch/pdfmake#1496]
i cann't find how to make it support for this rtl lang

**Comment by liborm85** [comment]
RTL is not supported now. Feature request: https://github.com/bpampuch/pdfmake/issues/184

**Comment by MohanadI** [comment]
here is an example of adding arabic font 

[pdfmake_arabic.zip](https://github.com/bpampuch/pdfmake/files/2460118/pdfmake_arabic.zip)

**Comment by Mostafa-m-tantawy** [comment]
but it suport arabic only or english only . is there is any way to use both

**Comment by Gil-Epshtain** [comment]
The problem with the Hebrew and Arabic support has nothing to do with the text direction (RTL, LTR). The problem is that makePdf uses `Roboto` as there default font-family. This font doesn't support Hebrew and Arabic. as you can see here: 
[Roboto - Google Fonts](https://fonts.google.com/specimen/Roboto?selection.family=Roboto:ital,wght@0,400;0,500;0,700;1,400&sidebar.open&preview.text=שלום&preview.text_type=custom)

Changing this font will solve the problem:
```
            pdfMake.fonts = {
                MyFontName: {
                    normal: 'my-font-regular.ttf',
                    bold: 'my-font-bold.ttf',
                    italics: 'my-font-italics.ttf',
                    bolditalics: 'my-font-bold-italics.ttf'
                }
            }
            const docDefinition = {
                content: '...',
                defaultStyle: {
                    font: 'MyFontName'
                }
            };
```

**Comment by sudanking** [comment]
> 
> 
> but it suport arabic only or english only . is there is any way to use both

did you find an answer or get a solution to use both?

**Comment by german-st** [comment]
Hello.

Joining. My [issue](https://github.com/bpampuch/pdfmake/issues/1812)

**Comment by michalMenda** [comment]
Will we find a way to support Hebrew?
