### ISSUE TITLE
How to use PDFKit standard PDF fonts

### ISSUE THREAD

**Issue by Focushift** [bpampuch/pdfmake#1517]
It is possible to use PDFKit standard fonts?

If we look at PDFKit example http://pdfkit.org/demo/browser.html
It is not required to load additional font to draw text with Times-Roman.
But looks like that pdfmake bundling not includes PDFKit files required for standard fonts support.

**Comment by blikblum** [comment]
#1523 allows to use afm fonts which is used by pdfkit to support the 14 PDF Standard fonts

It requires to store the afm font data without converting to buffer so the needed change

I abstracted the loading and configuration in PdfAssetsLoader class from https://github.com/blikblum/pdfmake-utils

A full example of how to setup Standard fonts can be found at: https://github.com/blikblum/pdfmake-playground/blob/master/src/setup/components.js#L9-L12

**Comment by liborm85** [comment]
Standard 14 fonts are supported by pdfmake on server-side by default.
But on client-side is not supported by default because it increate file about **700 kB**. And files are only with ANSI code page (only english characters). I'm implemented command for building with standard fonts by commit https://github.com/bpampuch/pdfmake/commit/903f767a255725f70e2fc962eea512522f571753.

How to use standard 14 fonts in pdfmake are described in [wiki page](https://github.com/bpampuch/pdfmake/wiki/Standard-14-fonts).

(reference https://github.com/bpampuch/pdfmake/issues/101)

**Comment by Focushift** [comment]
Ok, thanks.

Another question - if i need support for another languages, i just convert ttf font to afm and replace afm from pdfkit?

**Comment by schmidtc63** [comment]
I tried using the example code but I'm getting errors:  

 var PdfPrinter = require('pdfmake'); // generates error SCRIPT5022: Cannot find module 'pdfmake'
   var printer = new PdfPrinter(fonts);
   var fs = require('fs'); //generates error SCRIPT5022: Cannot find module 'fs'

Thank you for any assistance.

Chris
