### ISSUE TITLE
multiple times print/download changes the output

### ISSUE THREAD

**Issue by dd-vs** [bpampuch/pdfmake#1576]
I want to download and print the same pdf for that I do as follows

var docDefinition = {};
docDefinition.content = [
    {text: 'LINE1'},
    { canvas: [{ type: 'line', x1: 0, y1: 2, x2: 500, y2: 2,}] },
    {text: 'LINE2'},
]; 

pdfMake.createPdf(docDefinition).download();
pdfMake.createPdf(docDefinition).print();
But the in the pdf printed ie: generated second time i can see that line is shifted both horizontally and vertically. Further testing i knew that the amount the line is getting shifted equals to the margin and the content before it. If i call that download function multiple times each time the line get shifted by the above amount.

How to solve this issue? I want the exact same pdf no matter how many times it's generated.
[1ef87501-7633-4cdd-9301-7a62f847e1c2.pdf](https://github.com/bpampuch/pdfmake/files/2629712/1ef87501-7633-4cdd-9301-7a62f847e1c2.pdf)
[5e68873e-2522-4f8e-8f9e-962f265b9626.pdf](https://github.com/bpampuch/pdfmake/files/2629713/5e68873e-2522-4f8e-8f9e-962f265b9626.pdf)

**Comment by adrienblot** [comment]
The docDefinition object is not an immutable. Pdfmake use the same object in order to create the layout of the pdf. Making a deep clone of the docDefinition object before passing it to pdfmake should solve the issue.

**Comment by dd-vs** [comment]
> The docDefinition object is not an immutable. Pdfmake use the same object in order to create the layout of the pdf. Making a deep clone of the docDefinition object before passing it to pdfmake should solve the issue.

Object clone solves the issue, but each time i need a new object.

**Comment by toniojst** [comment]
How can create clone of code can you please gave me your code that i see how its work. Becuse i have same problem.

**Comment by BrunoJuchli** [comment]
@liborm85 changing this so that `docDefinition`, or rather the generated pdf, is immutable would make the library easier usable:

- less error prone
-- actually downloading / printing what i'm previewing
- less resource intensive
- expected behavior

It would be great if this could be considered in an upcoming version.

**Comment by ndl7** [comment]
I am generating a pdf and printing it like this:
`pdfMake.createPdf(pdf).download(defFileName);` which does indeed print the pdf properly. If I run the same code, which generates exactly the same pdf, some of the `this.docDefinition` in `var doc = printer.createPdfKitDocument(this.docDefinition, options);` (pdfmake.js) do not get populated and I do get the following error:
`Error: unsupported number: NaN
    at value (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:77387)
    at o.rect (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:113895)
    at P (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:67751)
    at d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:71960
    at i.createPdfKitDocument (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:72322)
    at u._createDoc (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:58116)
    at u.getBuffer (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:60094)
    at u.getBlob (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:59924)
    at u.download (d:s\d\node_modules\pdfmake\build\pdfmake.min.js:15:59354)
    at PrintService.push../src/app/core/services/print.service.ts.PrintService.download (d:\s\d\src\app\core\services\print.service.ts:68:33)`

To be more specific it's `_maxWidth`, `_minWidth` of a `table` object that are not set, which in turn produces the above error as the code cannot calculate width for table columns.

I believe this happens because of object mutability. Can anyone please give me a suggestion how to re-initialize the `pdfMake` object? I have tried `cloneDeep` but to no avail.

**Comment by fabianbehrendt** [comment]
@toniojst I know it's a really old issue, but maybe it still helps you :)
Using the example code from the author, it would look like this:

`var docDefinition = {};
docDefinition.content = [
{text: 'LINE1'},
{ canvas: [{ type: 'line', x1: 0, y1: 2, x2: 500, y2: 2,}] },
{text: 'LINE2'},
];

const createPdf = docDefinition => {
    return pdfMake.createPdf(JSON.parse(JSON.stringify(docDefinition)));
}

createPdf(docDefinition).download();
createPdf(docDefinition).print();`

Source:
https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy

**Comment by icobg123** [comment]
Using ```JSON.parse(JSON.stringify(docDefinition))``` removes the ability to use functions to generate header/footer or anywhere else within the docDefinition object.
To circumvent this issue and preserve usability of functions we can create a deep clone using lodash as follows:

```
import {cloneDeep} from "lodash";

const createPdf = (docDefinition) => {
    return pdfMake.createPdf(cloneDeep(docDefinition));
}

```
