### ISSUE TITLE
IOS Safari filename

### ISSUE THREAD

**Issue by imchivaa** [bpampuch/pdfmake#1657]
IOS Version: 11.4.1
PDFMake Version: 0.1.53

download() function in safari for IOS always return Unknown.pdf for the filename.
I've also tried to set the file name using `defaultFileName: myfile.pdf`, `title: myfile.pdf` and `download('myfile.pdf')` but both not working on safari for IOS. 

They works on browser in windows 10 & chrome in android P. Is there any way to force the name?

**Comment by viktoryia-makaranka** [comment]
the same issue

**Comment by evgeniy-vashchuk** [comment]
the same issue

**Comment by liborm85** [comment]
For download pdfmake using [FileSaver.js library](https://github.com/eligrey/FileSaver.js), you can create issue [there](https://github.com/eligrey/FileSaver.js/issues).

**Comment by Chuckv01** [comment]
Hitting this as well

**Comment by centurianii** [comment]
Use `saveAs()` which comes bundled from CDN version of this library:

Suppose we have a pdf definition like:
```
var pdfDefinition = {
   userPassword: '',
   ownerPassword: '',
   permissions: {
      printing: 'highResolution', //'lowResolution'
      modifying: false,
      copying: false,
      annotating: true,
      fillingForms: true,
      contentAccessibility: true,
      documentAssembly: true
   },
   info: {
      title: 'Title',
      author: 'My library',
      subject: 'Subject',
      keywords: '',
      creator: 'My library',
      producer: 'My library'
   },
   pageSize: 'A4',
   // 'portrait' or 'landscape'
   pageOrientation: 'portrait',
   // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
   pageMargins: [ 40, 60, 40, 60 ],
   styles: {
      'size-8': {
         fontSize: 8
      }
   },
   content: [{
      layout: 'headerLineOnly', //'noBorders', 'lightHorizontalLines',
      style: ['size-8'],   // add more...
      table: {
         headerRows: 1,
         dontBreakRows: true,
         keepWithHeaderRows: 1,
         widths: ['auto', '*'],  // just example
         body: [
            ['field A', 'field B'],
            ['data 1', 'data 2']
         ]
      }
   }]
}
```
Now create object:
```
var pdf = pdfMake.createPdf(pdfDefinition);
```
get blob and save:
```
var promise = pdf.getBlob();
promise.then((blob) => {
   try{
      saveAs(blob, 'myFilename.pdf');
   }catch(e){
      console.Warn('Download failed from a call to external library "saveAs".');
      return false;
   }
   return true;
});
```
Method `getBlob()` returns a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) object that when resolved it pass a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob) to the success handler that's why inside `then` we wrote `(blob) =>`.

**Comment by Chuckv01** [comment]
The PDF generates fine. The issue is on iOS Safari the filename always appears as "Unknown.pdf" The filename will be correct on all other browsers while iOS Safari always has it as `Unknown.pdf`:

![image](https://user-images.githubusercontent.com/1181306/79238375-28674380-7e24-11ea-8e4a-e635b89ae155.png)

**Comment by centurianii** [comment]
so you **do** use  `saveAs()` method and you can see your file in a download folder like it happens in Android but the problem is that iOS change the filename to `uknown`? seems strange indeed but not for iOS!
