### ISSUE TITLE
Consider readding yarn lock file

### ISSUE THREAD

**Issue by blikblum** [bpampuch/pdfmake#1747]
Recently the yarn lock file was removed from repository.

Generally is good advice to commit it

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494

In particular, i just cloned pdfmake 0.1 branch, installed dependencies and tried to run build but it failed because package unicode-trie 0.3.1 was installed instead of 0.2 (the former uses ES6 syntax). With the yarn lock file this would not happen.

**Comment by liborm85** [comment]
Version 0.1 worked correctly in released version (npm package), problem was only in devel/master.

yarn.lock/package-lock.json are needed primarily in applications. This is not a completely preferred approach in libraries, because then you restrict developers by fixing versions of 3rd libraries.
Set required versions in package.json file is sufficient for library.

**Comment by blikblum** [comment]
> yarn.lock/package-lock.json are needed primarily in applications. This is not a completely preferred approach in libraries,

Here's the reasoning for using in libraries: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

Most developers commit lock files.

Just as example, i will keep with somewhat popular libraries from somewhat experienced dev teams:

https://github.com/facebook/react

https://github.com/Polymer/lit-element/

**Comment by blikblum** [comment]
Closing since i opened this to help other devs. This does not affect me since i know how to handle it
