### ISSUE TITLE
Minor Table Border Color bug

### ISSUE THREAD

**Issue by dorothythurston** [bpampuch/pdfmake#1807]
This is probably a low priority bug since it is probably an edge case
![Screen Shot 2019-09-10 at 10 59 40 AM](https://user-images.githubusercontent.com/6642778/64625433-2e8ed080-d3ba-11e9-9581-6e3e7bb3d499.png)
 but when I was trying out the borderColor in the playground example in the first tables example I was able to see a bug when setting border to false for all border values:

```
		{
			style: 'tableExample',
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					[{ text: 'One value goes here', border: [false, false, false, false], borderColor: ['#00ffff', '#00ffff','#00ffff','#00ffff']}, 'Another one here', 'OK?']
				]
			}
		},
```

**Comment by rabraha3** [comment]
From what I can gather, the `TableProcessor` is checking if the current cell and previous cell (above or to the left for horizontal and vertical lines, respectively) have a `borderColor` property. If we check whether the previous cell has

1. `border` property and
2. `borderColor` property

Example, lines 177 - 180 (`0.1` branch):

```
bottomBorder = cellAbove.border ? cellAbove.border[3] : this.layout.defaultBorder;
if (cellAbove.borderColor && bottomBorder) {
    borderColor = cellAbove.borderColor[3];
}
```

`&& bottomBorder` added to check whether the previous cell's bottom border is `true` or not. This type of addition was made on lines 178, 187, 282, and 291.

Then the provided example works. There are other edge cases that do NOT work, i.e., if we ALSO have  manual layout callbacks defined. The issue I found after checking whether the border is set is that the top border for the "Plus another one here" cell (2nd to last) is 'red', not 'black' -- the layout "hLineColor" is set, instead of the node's '#000000' color.

```
{
    table: {
        body: [
            [
                {
                    text: 'One value goes here',
                    border: [false, false, false, false]
                },
                {
                    text: 'Another one here',
                    border: [false, false, false, false],
                },
                {
                    text: 'OK?',
                    border: [false, false, false, false],
                }
            ],
            [
                {
                    text: 'Second value goes here',
                    border: [false, false, false, false]
                },
                {
                    text: 'Plus another one here',
                    border: [true, true, true, true],
                    borderColor: ['#000000', '#000000', '#000000', '#000000']
                },
                'Great?'
            ]
        ]
    },
    layout: {
        vLineColor: () => 'magenta',
        hLineColor: () => 'red'
    }
}
```

**Comment by liborm85** [comment]
I wonder how this should be properly render, because it's more complicated.

Bottom line on cell "Another one here" is definitely wrong color, correctly it should be like this:
![bug-1C](https://user-images.githubusercontent.com/1298652/65027580-e4b66500-d93a-11e9-92ec-305db5873d0e.png)

But cell "One value goes here" have defined `borderColor: ['#00ffff', '#00ffff','#00ffff','#00ffff']` (meaning cyan border color) and  `border: [false, false, false, false]` (meaning no border - do not display this border).
Cell "Column 1" and "Another one here" has no border definition, then meaning border enabled and border color is black.

Then cyan border color is defined but disabled, probably correct result should be this:
![bug-1B](https://user-images.githubusercontent.com/1298652/65027915-74f4aa00-d93b-11e9-81ec-dda4a88293bc.png)

What do you think about it? Correct is first or second image? Second to me.

**Comment by liborm85** [comment]
Fixed by [commit](https://github.com/bpampuch/pdfmake/commit/5598691743bf23f1f4b5e37f3272cafcebeb4c8a) (master) and [commit](https://github.com/bpampuch/pdfmake/commit/945b10956e9cba985c9d80e2e332a23b1de94fe5) (in 0.1 branch).

Now renders:
![bug-1B](https://user-images.githubusercontent.com/1298652/65217412-4bab5980-dab4-11e9-993b-16780247a945.png)

**Comment by liborm85** [comment]
Re-fixed layout.hLineColor by [commit](https://github.com/bpampuch/pdfmake/commit/479a854a68fb6e34c490729d08807b72c2a73ca6) (master) and [commit](https://github.com/bpampuch/pdfmake/commit/ab82c47c8fab3789ea90e6c3f3e823990a16a915) (branch 0.1).

**Comment by pibubear** [comment]
@liborm85 Hey, I was trying to remove table 
![sscs (1)](https://user-images.githubusercontent.com/76561836/103133760-5058b780-46d2-11eb-8a49-6eeee052b91c.png)
borders from my inner tables, I'm using html-to-pdf module to convert it to pdf. Can you help me in this, I've been looking all over for this issue of mine but couldn't find any luck.
Thank you!

**Comment by Aymkdn** [comment]
It's Christmas so expect a few days before getting my help.

**Comment by pibubear** [comment]
:( cool. Thanks for replying though. Merry Christmas!

**Comment by Aymkdn** [comment]
> It's Christmas so expect a few days before getting my help.

Oh, sorry I thought this question was posted on my https://github.com/Aymkdn/html-to-pdfmake project, but it was on the PDFMake project that I don't own :-)

If I can share a tips, you probably want to check the "Tables" tab from http://pdfmake.org/playground.html. For example, you can have lighter inner borders like the below one:
![image](https://user-images.githubusercontent.com/946315/103203825-1a941880-48f6-11eb-9d9d-0f99a1b7ce16.png)

Then the code is defined in the Playground:
![image](https://user-images.githubusercontent.com/946315/103203857-34cdf680-48f6-11eb-95fc-51f550df3335.png)

The answer you're looking for is probably to use the `layout` property as shown above.
