### ISSUE TITLE
Open & download not working (IE11, Chrome) - build 0.1.15 

### ISSUE THREAD

**Issue by KajB** [bpampuch/pdfmake#181]
Hey,

First of all: great stuff! Keep working on this ;-)
Following the documentation I got the document definition set-up and passed it to the createPdf function, which works fine. But when I call open or download on that object, it fails silently. After some debugging, I found out that strict mode is preventing a object assignment on line 17815: 
**data = rowData[col] = this.styleStack.auto(data, measureCb(this, data));**
It is doing a assignment on a read-only variable here. The error is caught and nothing happens, as expected.

Then I made some changes myself (preventing the assignment) and let it run. Then it caught a undefined error on line 17813, because the row with the column didn't exist. 

I'm running the latest build (also tried earlier builds, same problem).
My doc definition object is as follows:

![ss](https://cloud.githubusercontent.com/assets/9351680/5935803/20ddd6f0-a6df-11e4-9293-2adc1eb4c266.png)

Thanks in advance,
Kaj

**Comment by Wabbala** [comment]
Hi KajB,

By looking at the code you supplied, I think the problem lies in how your columns are generated because of code error. 

1. 
Assuming you have 4 columns the variable columns should be ['filename', 'hits', 'totalbytes', 'totalbytesformatted'] instead of ['filename, hits, totalbytes, totalbytesformatted']
2. 
Your expectation of the variable columns after the for loop is wrong.
You got in the end an array of length *k* in which each entry is a string (**!**). Where as this actualy should be an array with length *m* which is equal to the number of columns (in your case 4).

So try fixing your code first :smiley:

**Comment by KajB** [comment]
You’re totally right! Jeesh, so stupid I didn’t see that. I have it working now. ;-)

Thanks for your reply,
Kaj
