### ISSUE TITLE
Header/Footer reset Page Counts

### ISSUE THREAD

**Issue by ephdisc** [bpampuch/pdfmake#210]
We're running batch reports. How would it be possible to reset the page count/page total for each iteration? Our report sizes are dynamic, so we can't use the modulus solution.

**Comment by jthoenes** [comment]
At the moment, I think this is impossible. The only way I can think of, is generating each individual report on it's own and than concatenating the pdfs using an external tool like pdftk.

**Comment by ephdisc** [comment]
Yeah, that's what I figured.  Appreciate the response.

**Comment by bchr02** [comment]
+1

**Comment by robstoll** [comment]
@jthoenes this is an old thread, so sorry for reviving. I have the same need and I was wondering if it would not be possible to change `addDynamicRepeatable` and pass `this.writer.context().getCurrentPage()` to the sizeFunction instead of `this.writer.context().getCurrentPage().pageSize`. This way I could determine the iteration based on a specific element on the CurrentPage
