### ISSUE TITLE
Use getBase64() with async / await function

### ISSUE THREAD

**Issue by kheber92** [bpampuch/pdfmake#2269]
I'm trying to convert a PDF created by using `pdfMake.createPdf()` to a base64 string.
Since I have asynchronous code (the base64 should be uploaded to Firebase Storage after creation), I'm looking for a solution to use the `getBase64()` with async / await.

What currently works is that I can log the created base64 string.
```
async generateCertificate(data) {

   let pdf_doc_generator = pdfMake.createPdf(data);

   pdf_doc_generator.getBase64((pdf_base64) => {
      // How to use the pdf_base64 string outside this function / make it async?
      console.log(pdf_base64);
   });

   // Upload base64 string and get path of uploaded file
   let upload_path = await this.uploadPdf(pdf_base64);

   return upload_path;
}
```

How can I make this async to re-use the generated `pdf_base64` string in my next functions?

**Comment by Cheesier** [comment]
You can wrap that function in a promise
`
const output = await new Promise(resolve => {
  pdf_doc_generator.getBase64((pdf_base64) => {
    console.log(pdf_base64);
    resolve(pdf_base64);
  });
})

let upload_path = await this.uploadPdf(output);

return upload_path;
`

**Comment by rvoelkel-nest** [comment]
I'm really struggling with the getBase64() method. What npm package do I have to install to use the promise variant of the getBase64 method? I don't want use the callback variant, because it does not give back errors. The code above is just a nice wrapper for when everything goes well. Currently I'm using a construct of timeouts to be able to guess when an error occurred. pdfmake is a great tool, but this part just bugs me.
