### ISSUE TITLE
Image with exif orientation tag

### ISSUE THREAD

**Issue by tarrant17** [bpampuch/pdfmake#2316]
Hi everybody,

It seems that PdfMake is ignoring the exif metadata tag "orientation". I dont know if its a bug or a feature not implemented.

I tested with two image with different "orientation" tag. One set to "Horizontal normal" and other with "90° CW". Both images are displayed in landscape style.

I made a sandbox project to reproduce :

https://codesandbox.io/s/pdfmake-forked-nzdm6?file=/src/index.js

Thanks for your reply and sorry for my english

**Comment by capc0** [comment]
With pdfmake version 0.2.15 which updated pdfkit to 0.15.1, the logic of `ignoreOrientation` of https://github.com/foliojs/pdfkit/blob/master/docs/images.md has landed in pdfmake. 

I have tested this with the landscape example images of https://github.com/ianare/exif-samples/tree/master/jpg/orientation.
Previously 7 out of the 8 test images where rotated, flipped and/or inverted in some way. With the new version all 8 images are rotated correctly. The only issue is that 4 of the images are stretched. This might be due to the `fit: [width, height]` logic. But I guess this is again a bug in pdfkit.

pdfmake@0.2.7

![image](https://github.com/user-attachments/assets/c226ed71-a6c2-43fb-a676-081c8af0ce42)


pdfmake@0.2.15

![image](https://github.com/user-attachments/assets/e3acb024-f833-4f16-b950-a37098ebe44c)


Nevertheless, the new version drastically improves EXIF support already!

**Comment by liborm85** [comment]
pdkit returns the original dimensions of image and in rendering swap dimensions according to the orientation. pdfmake ignores this behavior.

Fixed by commit https://github.com/bpampuch/pdfmake/commit/9052559f434349d42d7802f36be0863d8d7e304d.

New output:
![image](https://github.com/user-attachments/assets/4035548a-b0bc-413c-8982-b72ee9a9430f)

**Comment by liborm85** [comment]
Released in version 0.2.16.
