### ISSUE TITLE
header and footer follow pageMagins?

### ISSUE THREAD

**Issue by BobbyHe** [bpampuch/pdfmake#241]
***Problem solved by enlarge page margin***My bad!

I have two issues about header and footer.
1. Header can only be added as function, otherwise it won't show up.
2. I can't set top margin for header. I have a multi-line header, and if I set top margin for the header or any line of the header, only one line shows up, and all other styles are gone. 
![image](https://cloud.githubusercontent.com/assets/3663418/6693508/ad8a2834-cc90-11e4-8687-6954b9132ffb.png)
![image](https://cloud.githubusercontent.com/assets/3663418/6693516/be54142c-cc90-11e4-9801-abc661fcb41c.png)

**Comment by jthoenes** [comment]
Hi @BobbyHe, 

Problem 1 has been fixed with #227 and will be in the next release.

For Problem 2 you are correct, header and footer live outside of the page margin. So you need to increase the pageMargin top for your problem, at least that's what I assume. If that's not the case, feel free to re-open the issue.

BTW: It's good practice to open one issue per problem. 

Best regards
Johannes

**Comment by jthoenes** [comment]
Hi @BobbyHe, 

Problem 1 has been fixed with #227 and will be in the next release.

For Problem 2 you are correct, header and footer live outside of the page margin. So you need to increase the pageMargin top for your problem, at least that's what I assume. If that's not the case, feel free to re-open the issue.

BTW: It's good practice to open one issue per problem. 

Best regards
Johannes
