### ISSUE TITLE
Unable to use Image URL for fetching and rendering it to PDF

### ISSUE THREAD

**Issue by qur786** [bpampuch/pdfmake#2416]
We are trying to use `Image URL` to fetch images and to render it in the PDF as per the docs.
```
......
{
      // in browser is supported loading images via url from reference by name in images
      image: 'snow'
    },
  ],
  images: {
    // in browser is supported loading images via url (https or http protocol) (minimal version: 0.1.67)
    snow: 'https://picsum.photos/seed/picsum/200/300'
  }
};
```

 Ref: https://pdfmake.github.io/docs/0.1/document-definition-object/images/

But to our dismay, the Browser is consistenly throwing this error.
`NOTE: the image used is publicly accessible`

```
Access to fetch at '*************************/**********/*********-2.png' from origin 'http://localhost:6001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
We have already tried Changing CORS config in our aws server.

is there any issue with rendering images with `publicly accessible URL` in `pdfmake` ?

**Comment by liborm85** [comment]
CORS are decribed in [wikipedia](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

Your image on url `*************************/**********/*********-2.png` not return `Access-Control-Allow-Origin` headers as require CORS. Which is also written in error - "No 'Access-Control-Allow-Origin' header is present on the requested resource."

You have to add to headers `Access-Control-Allow-Origin` on your url `*************************/**********/*********-2.png`.

**Comment by sintrahq** [comment]
Hello, the problem is on cached images. if the image is already loaded in the html as img src that one is in the browser cache. when fetched again from prdfmake as fetch() the image is retrieved from the cache but it doesn't contains the header Access-Control-Allow-Origin and youll be blocked by the browser. the lib can't get the image and the pdf is not created.
to fix this we've added a cache bust eg: imagesrc?v=rand_number 

we've spent tons of time to figure out this weird issue.
