### ISSUE TITLE
How to display total of page at first page?

### ISSUE THREAD

**Issue by Attachai77** [bpampuch/pdfmake#2536]

**Comment by xDivisionByZerox** [comment]
You might want to give some more information about what you are exactly looking for.
Otherwise you can read about [dynamic headers and footers](https://[pdfmake](https://pdfmake.github.io/docs/0.1/document-definition-object/headers-footers/).github.io/docs/0.1/document-definition-object/headers-footers/).

By providing a function to the `header` or `footer` property of the document definition you receive the total number of pages as the second argument:

```js
const documentDefinition = {
  footer: (
    // the current page number
    currentPage, 
    // the total page number
    pageCount,
  ) => { 
    return `Footer: ${currentPage} of ${pageCount}`; 
  },
  header: (currentPage, pageCount) => {
    return `Header: ${currentPage} of ${pageCount}`,
  },
};
```

This will generate a page like this:

|Header|Footer|
|---|---|
| ![image](https://user-images.githubusercontent.com/77127505/228326396-e9ed0c19-3daa-4e94-bfcf-305d6ec63499.png) | ![image](https://user-images.githubusercontent.com/77127505/228326505-5a11845a-ea15-4209-946c-40c9c2cb097a.png) |

<details>

<summary>Playground code</summary>

```js
var dd = {
    footer: (
        // the current page number
        currentPage, 
        // the total page number
        pageCount
    ) => { 
        return {
            text: `Footer: ${currentPage} of ${pageCount}`,
            margin: 20,
        };
    },
    header: (currentPage, pageCount) => {
        return {
            text: `Header: ${currentPage} of ${pageCount}`,
            margin: 20,
        };
    },
    content: [
        {
            text: '',
            pageBreak: 'after',
        },
        {
            text: '',
            pageBreak: 'after'
        },
        {
            text: '',
            pageBreak: 'after'
        },
    ],
};
```

</details>
