### ISSUE TITLE
Why is the QR code different in size?

### ISSUE THREAD

**Issue by asavchinnikov** [bpampuch/pdfmake#2655]
Hi!
Why is the fit QR code and SVG fit different in size?
I set the same size for QR and SVG, but as a result the QR is smaller:

```
var dd = {
	content: [
		{
            qr: 'pdfmake',
            fit: 200,
            background: 'gray'
        },
        {
            svg: '<svg width="200" height="200"><rect width="200" height="200" style="fill:red" /></svg>',
            fit: [200, 200]
        }
	]
};
```

**Comment by liborm85** [comment]
Because QR code can only take on certain sizes.

In code is this: https://github.com/bpampuch/pdfmake/blob/0.2.8/src/qrEnc.js#L749
Your QR have 21 data points on width, fit is 200 => then 200 / 21 = 9,5 = round to 9 => 21 * 9 = **189**
Then QR code have real width 189 points. This is expected behavior.
