### ISSUE TITLE
Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)

### ISSUE THREAD

**Issue by andrewhamili** [bpampuch/pdfmake#2767]
#1501 

[https://github.com/andrewhamili/nestjs-pdfmake.git](url)

**Comment by andrewhamili** [comment]
Currently experiencing this issue.

**Comment by liborm85** [comment]
Throwed error message is wrong, fixed by commit https://github.com/bpampuch/pdfmake/commit/757735fe95f657ef0ba2308b4e2806d5c04077cd. Released in version 0.2.12.

Correct error message is:
`Invalid image: Not supported image definition: {"url":"https://picsum.photos/640/480"}
Images dictionary should contain dataURL entries (or local file paths in node.js)`

Loading images from url addresses is supported only on browser version of pdfmake. On server (on node.js) is not supported, see 
[documenation](https://pdfmake.github.io/docs/0.1/document-definition-object/images/):
>    // **in browser** is supported loading images via url (https or http protocol) (minimal version: 0.1.67)
>    snow: 'https://picsum.photos/seed/picsum/200/300',

Will be solved in version 0.3, see https://github.com/bpampuch/pdfmake/issues/2375.
