### ISSUE TITLE
Cannot read from $scope

### ISSUE THREAD

**Issue by rebelholic** [bpampuch/pdfmake#296]
Hello,

I have an ionic application with PDF download feature (with this plugin). When generating data to create a PDF, this plugin just read data from $localstorage (such as $localstorage.dataname.a) not from $scope. If generate from $scope will get blank text for PDF result.
Its my example variable for this problem:

         var docDefinition = {
        content: [
    { text: $scope.model.name }
       ],
      };

How I can fix it?
Thanks for support

**Comment by rebelholic** [comment]
Its [my repo](https://github.com/rebelholic/Ionic-PDF-Make-LocalStorage) for this problem

**Comment by jthoenes** [comment]
A guess it might be because on the AngularJS $scope there are other things than just pure javascript objects. Maybe watchers or something?

Make sure you pass a plain JavaScript object as document definition. If that does not work, please post the resulting document definition and error messages is you get any in your console.

Hint: Please don't expect anybody to debug a whole project for you. When you provide code, make sure you use as little as possible code to reproduce your issue. I don't want to click through a menu or read a 'getting started guide' of a framework before I can understand you problem.
