### ISSUE TITLE
Page size unit

### ISSUE THREAD

**Issue by marccollin** [bpampuch/pdfmake#359]
Hi

what is the unit used for page size ?

I don't find this information in the documentation.

**Comment by Hejado** [comment]
Anybody? I read in #334 that margins are provided in inch, but this is definitely not true for pageSize...

    pageSize: {height: 90, width: 38}

is really tiny.

I think it's strange, that these properties use different units. Did I miss a way to specify which unit is used?

**Comment by tcsaddul** [comment]
Try,

pageSize: { width: w * 72, height: h * 72 },
 


     On Tuesday, September 8, 2015 8:33 PM, Nico Prediger <notifications@github.com> wrote:
   

 Anybody? I read in #334 that margins are provided in inch, but this is definitely not true for pageSize...pageSize: {height: 90, width: 38}
is really tiny.I think it's strange, that these properties use different units. Did I miss a way to specify which unit is used?—

**Comment by Hejado** [comment]
Thanks, that works. In pageSize as well as pageMargins...

I can get from mm to inch by multiplying with 0.0393700787, so that's what I did after reading #334, but it seems like I only get 1/72 of an inch because of $someReason ?!

Anyway, I can move on now, thank you very much.

**Comment by dpeczek** [comment]
For me it seems like 72 is dpi of the document, so size and margins units are simple pixels. This is only my suppose.

**Comment by Serios** [comment]
Actually sizes and margins are in points (pt)

**Comment by viklele** [comment]
Actually they are in TWIPS. 

If you want to set the page size to 5 inch by 6 inch, set the values 5 * 72 and 6 * 72. Same with margin.

**Comment by jeffrey-cochran** [comment]
Something tells me they are not in TWIPS. Namely, a TWIP seems to be 1/1440 of an inch, and that would imply the standard page sizes given are absurdly small ([see the documentation](https://github.com/bpampuch/pdfmake/blob/ce8a2609986a3bf6e3c83f61741d4c56ca0b4ca0/src/standardPageSizes.js)). In fact, I believe the default page size is defined as A4 in printer.js: width=595.28, height=841.89. If it were twips, this would be fractions of an inch. Knowing that the true width of the A4 standard is 8.3 inches, we would expect that to imply that 595.28/8.3=71.7 is the scaling factor (call it dpi or whatever you want). However, this is almost certainly just rounding error, and in fact, the scaling factor from inches to *insert whatever these mysterious units ACTUALLY are* is 72 as mentioned above. In any case, I do believe that the margins use the same units, and I believe their default value is 40 on each side.

**Comment by viklele** [comment]
In fact you are right. It is not TWIPS, my bad. The mysterious unit is "point". One inch is 72 point size. Point is the unit normally used to specify font size.

**Comment by gsc89** [comment]
It would be handy to be able to define page sizes in mm or inches for me because im am printing to a zebra printer, 72 DPI is standard monitor resolution but the printer I am using is 203DPI so I will adjust / test and report back.

**Comment by mandtcampos** [comment]
"In printers' measures, there are 12 points to a pica and 6 picas in an inch. So, 12 x 6 = 72; there are 72 points in an inch. And since points and pixels are the same thing, there are 72 pixels in an inch, too. So, if you want something on screen to be 4 inches wide: 4 x 72 = 288."

https://www.dougv.com/2007/11/the-relationships-between-pixels-points-picas-dots-and-inches/

**Comment by liborm85** [comment]
Answered.

**Comment by boom235** [comment]
Why is this answered? I am very confused that this is not part of the documentation.... Isn't this like THE main think when creating and printing PDF? What if I need a general page margin of 1cm (10mm)? If the unit is inches, I could easily calculate this but if it is points it depends on the monitor I am using isn't it? Why is the documentation not saying which unit this is? 
Best regards

**Comment by doc82** [comment]
Could this get added to the documentation please?

**Comment by danramosd** [comment]
Bueller???

**Comment by mandtcampos** [comment]
How/Where are you wanting this added to the documentation? Is that something I can even do?

**Comment by AnalyzePlatypus** [comment]
Use this function to convert millimeters to pdfmake `point`s:

```js
const MILLIMETERS_IN_INCH = 25.4;
const POINTS_IN_INCH = 72;

function mmToPoints(mm) {
  const inches = mm / MILLIMETERS_IN_INCH;
  return inches * POINTS_IN_INCH;
}
```

**Comment by Jeremias-Nater** [comment]
This was really confusing to me since i have to do this based on a design which was delivered to me in pixel sizes (as part of preview in web application). 

At least knowing that the unit used here is Pt. i was able to find out that default A4 Page is 595.35 x 841.995 Pts which lets me convert the px width to a unit usable in the pdf.

I think the fact that Pt. are used belongs into the documentation and maybe even a list of values used for the different sizes in the section "Page dimensions and orientation". [Here's a list](https://www.a4-size.com/a4-size-in-point/) containing the information for different formats (which i hope is equal to the values used in makePdf-code).
