### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by conan311** [bpampuch/pdfmake#366]
I am trying to add a watermark but ended up with some weird and random characters printed no matter what I provide in watermark. I put this question on stackoverflow but got no response. 
Please see it for more details.

http://stackoverflow.com/questions/31691355/watermark-using-pdfmake

**Comment by driedger** [comment]
I am having the same issue. Any help would be greatly appreciated.

**Comment by driedger** [comment]
I can't say as I have a solution to this problem, but I have made it work for me. It seems the `renderWatermark()` function at or around line 465 has problems with encoding the font.
`var encoded = watermark.font.encode(watermark.text);` returns a blank string, and doesnt have the extended properties the function is looking for later on.

By changing 
`pdfKitDoc.addContent('/' + encoded.fontId + ' ' + watermark.size.fontSize + ' Tf');` to
`pdfKitDoc.addContent('/ ' + watermark.size.fontSize + ' Tf');`
and
`pdfKitDoc.addContent('<' + encoded.encodedText + '> Tj');` to
`pdfKitDoc.addContent('(' + watermark.text + ') Tj');`

I was able to get a watermark to show up in the correct position, albeit with a generic font rather than anything I had selected.

**Comment by tneil** [comment]
Curious if the outstanding pull request from liborm85 will be considered to be merged into the project.  We are also looking to use the watermark feature but are receiving font exceptions when we're attempting to use it.

**Comment by tneil** [comment]
For us we were able to get it working by changing the line 

`font: fontProvider.provideFont(fontProvider[defaultFont], false, false),`

to 

`font: fontProvider.provideFont(defaultFont, false, false),`

in **LayoutBuilder.prototype.addWatermark**

**Comment by rpocklin** [comment]
@tneil your solution works well, thanks.

**Comment by liborm85** [comment]
Fixed by https://github.com/bpampuch/pdfmake/pull/492
