### ISSUE TITLE
Windows 10 Edge Browser Fail

### ISSUE THREAD

**Issue by billycomic** [bpampuch/pdfmake#392]
We use pdfmake and having issue with Windows 10 Edge browser. On Chrome, FireFox, get perfect pop-out pdf generated. On IE generates download link for the file as designed. But, on new Edge browser from microsoft, I see nothing. It opens new tab as if it's going to build pdf, but nothing. No errors in console. 

Haven't seen reports of this up to this point. Is there a way to work around this or extend for new browser detection?

Thanks,

B

**Comment by DavidWeil** [comment]
Is pdfmake generating the PDF file in a re-entrant manner?  We have a servlet that generates PDF reports and returns a one-time context path, which responds with an inline PDF.  What we observe (from wireshark) is Edge re-issuing the request once the PDF viewer opens in a new browser tab (instead of passing the response content to the new tab).  Since the path is one-time (the backing temporary file is delete on close), Edge fails to display the PDF.  (In our case the error is easy to see, since the servlet generates a 500 error for file-not-found.)

**Comment by liborm85** [comment]
Bug is same as https://github.com/bpampuch/pdfmake/issues/693.
