### ISSUE TITLE
How to use indents in paragraphs?

### ISSUE THREAD

**Issue by and7ey** [bpampuch/pdfmake#448]
I would like to start first line of each paragraph with an indent, for ex.
`New paragraph start`
should be replaced with
`____New paragraph start`
(_ is shown above instead of space)

I tried to use 4 spaces, \t, but with no success.

**Comment by LeoLPF** [comment]
from now on ,pdfmake.js may not support 'text-indent'. but you can add the 'text-indent' by yourself in the function 'measure(fontProvider, textArray, styleContextStack)'.

**Comment by frwendling** [comment]
Found a cheap and dirty trick by copying/pasting the U+2007 ' ' character 8 times (see https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation).

**Comment by creaturerigger** [comment]
Hello i am using times new roman as pdfMake.font and to indent i added "\u0009" at the beginning of the first line of the paragraph but it reacts weird and it makes a huge space between the first word and the second. I think the source of this problem is times new roman font because when i do this with the default font of pdfmake which is roboto it behaves properly. Has anyone any idea?

**Comment by liborm85** [comment]
https://github.com/bpampuch/pdfmake/issues/558
