### ISSUE TITLE
Avoid pdfmake if you are going to generate over 20 pages. 

### ISSUE THREAD

**Issue by jerry8050** [bpampuch/pdfmake#464]
Here's why 
![pdfmake](https://cloud.githubusercontent.com/assets/3515124/11827493/572ce2dc-a341-11e5-8b53-5d9286f13222.png)

**Comment by Seurimas** [comment]
There are a few fixes lying around which improve performance substantially. Namely fixes listen in #280 can be life savers.

**Comment by no-more** [comment]
Hi, I confirm the fix is really great. But when will it be merged?

This is a great tool, thanks a lot for all your work but it seems the project is almost dead. I understand you might not have time for this project anymore.

I don't know how many people are using this (great) tools, but maybe not that much. It seems the developers are all gone which is very sad because this is a great product.

My question is, is there an alternative solution for a production environment? I need to generate huge pdf reports and there's some glitch with this version. 

Once again, thanks a lot for this great tool and all your work.

**Comment by bpampuch** [comment]
Hi, I'll merge pull requests tonight

W dniu sob., 19.12.2015 o 06:16 no-more <notifications@github.com>
napisał(a):

**Comment by Edersonestevo** [comment]
Olá, você resolveu o problema?

**Comment by jerry8050** [comment]
Hi,
I did see the fix that you are referring to. Correct me if I'm wrong but I think it's for client side pdf generation and I haven't seen a fix for server side generation yet. 

Thanks

**Comment by timctrahan** [comment]
I'm using the client side version of this, but in researching the issue, and finding that in a new build, the fix for #280 changes the resulting javascript file, not what is causing it (which i'm guessing is why it hasn't been merged yet)

I found that the actual culprit resides in

   [12] (webpack)/~/node-libs-browser/~/readable-stream/lib/_stream_readable.js 26 kB {0} [built]

Applying the change inside there will make it survive a build.  Obviously changing a node package isn't optimal, but I'm GUESSING that would fix the issue for server side generation as well.

**Comment by liborm85** [comment]
New version with fix released.
