### ISSUE TITLE
Horizontal line?

### ISSUE THREAD

**Issue by ljack** [bpampuch/pdfmake#514]
Hope it's ok to create an issue about this. I tried to search the documents but I might have missed how to create a horizontal line?

**Comment by bekann** [comment]
You only can solve this with a workaround. As far as I know, pdfmake does not provide an drawing API

- use an Image containing a line

- Create a table with layout headeronly you must define an empty body, otherwise the line would not appear:

```
var dd = {
	content: [
	    {
    		    	        	  table : {
    		    	        		  headerRows : 1,
    		    	        		  widths: [200],
    		    	        		  body : [
    		    	        		          [''],
    		    	        		          ['']
    		    	        		          ]
    		    	        	  },
    		    	        	  layout : 'headerLineOnly'
    		    	          }
			]
}
```
The width defines the length of the line

Code tested in Playgorund.

**Comment by ljack** [comment]
Thanks! Works like a charm ;) Workaround works ;)
