### ISSUE TITLE
Preview in browser

### ISSUE THREAD

**Issue by g41n** [bpampuch/pdfmake#519]
I need a preview of the PDF in browser... can I have it as image or HTML? Is there any method like "toCanvas" or something like that?

**Comment by ryanlin1986** [comment]
You should use pdf.js to do this
https://github.com/mozilla/pdf.js

**Comment by g41n** [comment]
Thanks for the response but I need something to show it before the PDF generation.
Does the JSON for the doc definition follow some standard? In this case, is there and interpreter to convert it into HTML?

**Comment by daniellizik-sc** [comment]
You can take the base64 data url and use it as the `src` attribute in an iframe. See the [jspdf](https://parall.ax/products/jspdf) homepage for an example.

**Comment by daniellizik** [comment]
You can take the base64 data url and use it as the `src` attribute in an iframe. See the [jspdf](https://parall.ax/products/jspdf) homepage for an example.

**Comment by stodolos** [comment]
The getBase64 method yielded the following error for me:

> HTTP Error 414. The request URL is too long.

The getDataUrl method seems to work just fine though.  The problem is with IE though.  Nothing appears...  

I was wondering if it's possible to mix both pdfMake and pdf.js (which works in IE) together.  I only see how to use pdf.js with an actual file, but not with an object or dataUri or something.

Any thoughts?

**Comment by tlk** [comment]
Perhaps this could be used: http://stackoverflow.com/a/12094943/936466

**Comment by liborm85** [comment]
Answered.
