### ISSUE TITLE
Does this support layers (like z-index in HTML)?

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [bpampuch/pdfmake#612]
I want to make some reports and y need to put a watermark over all the page's content in some cases. Can I do some like this? I haven't find any information about this. If it's no possible, it could be an interesting feature. 

Thanks.

**Comment by ryanlin1986** [comment]
I'm facing the same problem, the watermark over page's content, any plan to have this feature added?

**Comment by tneil** [comment]
Have you tried using the **watermark** property of the root PDF document.  We have used it in our implementation and it works quite well.  It only allows for a string value, but that is all we needed.

You could also do a translucent image and set its absolute position to float over the content by setting the image's **absolultePosition** property

https://github.com/bpampuch/pdfmake/blob/master/examples/absolute.js

But for a document where you want the watermark on each page I would recommend the **watermark** property so that you don't have to repeat a translucent image on each page.

**Comment by ryanlin1986** [comment]
Thanks a lot, this is just what we need.

**Comment by liborm85** [comment]
Watermark formatting is supported in version 0.1.22.
