### ISSUE TITLE
Is it possible to apply bold style to table cell?

### ISSUE THREAD

**Issue by abhimunna** [bpampuch/pdfmake#756]

**Comment by aconran** [comment]
Rather than just putting a plain string in the cell body, you can put a nested object and use the _bold_ attribute or build it into a style.

Here is a docDefinition showing how to do it either way that you can copy/paste in the playground.
http://pdfmake.org/playground.html

`var dd = {
	content: [
		'The following table has nothing more than a body array',
		{
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					[
					    {text: 'One value goes here',bold: true},
    					'Another one here', 
    					{text: 'OK?', style: 'boldTd'}
    				]
				]
			}
		}
	],
	styles: {
		boldTd: {
		    bold: true
		}
	}
}`
