### ISSUE TITLE
Maintenance project

### ISSUE THREAD

**Issue by liborm85** [bpampuch/pdfmake#776]
As it is currently with this project?

Earlier @miltador created a fork of the project and development again after some time had stopped.
Now project @danawoodman maintained, but its activity is low, probably does not have that much time.

We need merge same PRs (#775, #759), because currently is not correctly build pdfmake.

@bpampuch , @danawoodman : They need more maintainers. I can help if I got permission for contributing to project. Is necessary merging pull requests a clean up issues.

It would be a shame to stopped this project...

**Comment by miltador** [comment]
I have already created a PR which merges my fork back and fixes some more issues. I am waiting for reviewing it. I am actually watching the issues here and respond from time to time. But slow review process is discouriging. I can help with maintainig project too.11:32, 9 грудня 2016 р., "Libor M." <notifications@github.com>:As it is currently with this project?
Earlier @miltador created a fork of the project and development again after some time had stopped.
Now project @danawoodman maintained, but its activity is low, probably does not have that much time.
We need merge same PRs (#775, #759), because currently is not correctly build pdfmake.
@bpampuch , @danawoodman : They need more maintainers. I can help if I got permission for contributing to project. Is necessary merging pull requests a clean up issues.
It would be a shame to stopped this project...

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Надіслано з мобільної програми Яндекс.Пошти

**Comment by danawoodman** [comment]
I don't have the ability to add collaborators, only @bpampuch does. I also don't have a ton of time to dedicate to working on this project unfortunately, especially since I don't know the codebase very well. 

I've entertained creating a new repo with a fresh codebase to build a React PDF generation library with similar features but probably don't have the time to do it... 😢

**Comment by liborm85** [comment]
@danawoodman Thank you for answer.

Does anyone know how to contact @bpampuch?

**Comment by bpampuch** [comment]
through github ;) hold on

**Comment by liborm85** [comment]
@bpampuch Please can you add me as collaborator ?

**Comment by bpampuch** [comment]
done

**Comment by sepsol** [comment]
@liborm85 @bpampuch I was curious about the current maintenance status of the project. It seems to have become stall for the last couple of years. And there seems to be an ongoing migration to the newer JavaScript syntax in the master branch.

I noticed:
- There isn't any message regarding maintainer/help needed. 
- I don't see any `CONTRIBUTING.md` documents. 
- And the source code doesn't have any `watch` scripts that would allow for the `debugger;` usage to make development easier since:
    -  `console.log()` can't capture the nested data, 
    - and `JSON.stringify()` does not work because of the "circular structure" of the data, 
    - and there are no Typescript type declarations to get autocomplete.
- And lastly, there are just so many issues and PRs open.

All of these issues combined makes it really hard for a new developer to contribute. And the current maintenance situation creates doubts for someone that is trying to evaluate whether they should use this library reliably. This project is really great and it is just so unfortunate if it dies. I would like to offer my help but I don't know how much I would be able to contribute.
