### ISSUE TITLE
[META] Documentation additions

### ISSUE THREAD

**Issue by miltador** [bpampuch/pdfmake#781]
This is meta issue related to documentation improvement.
Some new features where added, and also there are some old ones which aren't well documented.
Trying to gather them here.

- [x] Document setting filename for `open` and `download` methods (see #680)
- [x] Documentation for building custom fonts (see #785)

**Comment by eldesgonzales** [comment]
I would like to ask for a documentation too regarding on different headers and footers on the first page of the document though it seems easy, but if someone rely on the library too much, it'll hard for them to figure out how. So I did a code here:
[https://github.com/bpampuch/pdfmake/issues/178#issuecomment-274005757](url)

This is very helpful on everyone since it's a common thing to do. I hope someone can add it on the documentation.

**Comment by liborm85** [comment]
documentation updated - https://github.com/bpampuch/pdfmake/commit/5a1db63881b9f85e2abd18e64aa001b8699d75f9
