### ISSUE TITLE
Import pdfmake in Meteor

### ISSUE THREAD

**Issue by Kolyasya** [bpampuch/pdfmake#815]
Hello, I try to use pdfmake in my Meteor app, but have an error just after import

I've installed pdfmake with npm

`import pdfmake from 'pdfmake';`

Error in browser console:

```
index.js:10 Uncaught TypeError: fs.readFileSync is not a function
    at meteorInstall.node_modules.unicode-properties.index.js (index.js:10)
    at fileEvaluate (install.js:153)
    at require (install.js:82)
    at meteorInstall.node_modules.fontkit.index.js (index.js:28)
    at fileEvaluate (install.js:153)
    at require (install.js:82)
    at font.js:5
    at meteorInstall.node_modules.pdfkit.js.font.js (font.js:75)
    at fileEvaluate (install.js:153)
    at require (install.js:82)
```

Do you have any suggestions how to fix it?

**Comment by liborm85** [comment]
Fontkit new version is not fully compatible with pdfmake.

New released version of pdfmake 0.1.24 solves this problem.

**Comment by Kolyasya** [comment]
@liborm85 updated pdfmake verstion and still have the same issue

**Comment by liborm85** [comment]
@Kolyasya Hmmm, I see it, this is another problem.
I can't work with Meteor. But from error message is seen, it doesn't use a compiled `build` folder, but `src`.

Error is throw in package unicode-properties, specifically in the file unicode-properties/index.js:

> ...
> fs = require('fs');
>
>trie = new UnicodeTrie(**fs.readFileSync**(__dirname + '/data.trie'));
> ...

In the file is variable fs corectly formed, as shown in sample, I don't know why Meteor have problem with this...

**Comment by ThisSentenceIsFalse** [comment]
Having similar issue with Meteor not starting up - our project uses a [Webpack integration](https://github.com/thereactivestack-legacy/meteor-webpack):

```
Error: ENOENT: no such file or directory, open 'node_modules/unicode-properties/data.trie'
W20170116-13:07:43.339(2)? (STDERR)     at Error (native)
W20170116-13:07:43.339(2)? (STDERR)     at Object.fs.openSync (fs.js:549:18)
W20170116-13:07:43.339(2)? (STDERR)     at Object.fs.readFileSync (fs.js:397:15)
W20170116-13:07:43.340(2)? (STDERR)     at Object.<anonymous> (webpack:///~/unicode-properties/index.js:13:1)
W20170116-13:07:43.340(2)? (STDERR)     at Object.cptable.version (webpack:///~/unicode-properties/index.js:144:1)
W20170116-13:07:43.340(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap eb8954843c30dea6ba98:22:1)
W20170116-13:07:43.341(2)? (STDERR)     at Object.<anonymous> (webpack:///~/fontkit/index.js:31:1)
W20170116-13:07:43.341(2)? (STDERR)     at Object.exports.__esModule (webpack:///~/fontkit/index.js:13971:1)
W20170116-13:07:43.341(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap eb8954843c30dea6ba98:22:1)
W20170116-13:07:43.341(2)? (STDERR)     at Object.<anonymous> (webpack:///~/pdfkit/js/font.js:8:1)
```

The difference is that it doesn't find a file rather than not having the `fs` function. No problems until I updated the npm dependencies. Very interested in a solution...

**Comment by magbeat** [comment]
Had quite some trouble to get it up and running with the Angular CLI. Basically had the same error message. I installed it via yarn (npm) which in turn installs quite a few dependencies (pdfkit, fontkit, unicode-properties). unicode-properties was the problem in my case, because fs.readFileSync is not available in the browser.

Long story short: I created a simple browserify package, where I use the prebuilt version of pdfmake. There is a repo and a short howto on https://github.com/EcoLogicAG/pdfmake-browserify

Maybe this is of some use for somebody.

**Comment by liborm85** [comment]
@ThisSentenceIsFalse Is installed module unicode-properties in folder? Exists file `node_modules/unicode-properties/data.trie`?
Is possible use compiled version from `build` folder? (It contains all the dependencies/external files)

**Comment by ThisSentenceIsFalse** [comment]
> @ThisSentenceIsFalse Is installed module unicode-properties in folder? Exists file node_modules/unicode-properties/data.trie?

I did find the `node_modules/unicode-properties/data.trie` file (`node_modules` at top-level). I am importing pdfmake in a Node environment. 

> Is possible use compiled version from build folder? (It contains all the dependencies/external files)

Tested it, seems to work fine, going with this for now. Thank you.

In my case I believe it might be a webpack problem, since the integration I am using (not for much longer however) configures much for me, including resolving __dirname relative to the project context.
