### ISSUE TITLE
Empty PDF generated for large image

### ISSUE THREAD

**Issue by AswarthaA** [bpampuch/pdfmake#855]
Attached image is generated by html2canvas and I am trying to save it as PDF. But pdf is gerating empty document with two pages. 

Can any one help to solve this?

![download](https://cloud.githubusercontent.com/assets/7702834/22634506/67cdc7cc-ebf8-11e6-8c05-e95997f1a8bf.png)

 html2canvas(document.getElementById("myTable"), {
            onrendered: function (canvas) { 
                var data = canvas.toDataURL(); 
                var docDefinition = {
                    content: [{
                        image: data
                    }]
                };
                pdfMake.createPdf(docDefinition).download("Consolidated_Transcript.pdf");
            }
        });

**Comment by bhericher** [comment]
The generation if the image is asynchronous. You must wait its completion and generate the pdf after the onload event : use a timeout or, better, a promise.

**Comment by liborm85** [comment]
If image is larger than page will not be displayed.

**Comment by AswarthaA** [comment]
@liborm85  so alerternative is to generate individual table and generate PDF?

**Comment by seanfuture** [comment]
Thanks for comments here - By adding `fit: [590, 100000]` to the image definition the image then displayed where before the page was blank

**Comment by AswarthaA** [comment]
@seanfuture let me try out this approach also. For now we are generating individual images and generating pdf.

**Comment by wilsaj** [comment]
I'm also running into this.

It's only a problem if the image overflows the height of the page. I think the desired behavior would be for the image to just just show the part of the image that fits on the page instead of a blank image. This is what happens with images that are wider than fit on the page.

Copy / pasting this into the [playground](http://pdfmake.org/playground.html) demonstrates the issue:

```
var dd = {
  content: [
    {
      text: 'The following page displays correctly with the image',
      pageBreak: 'after'
    },
    {
      image: 'sampleImage.jpg',
      height: 761,
    },
    {
      text: 'The following page does not display correctly - there are just two blank pages',
      pageBreak: 'after'
    },
    {
      image: 'sampleImage.jpg',
      height: 762,
    },
  ],
}
```

It only renders the first image, the second one is just two blank pages:
<img width="72" alt="screen shot 2017-06-04 at 11 00 08 am" src="https://cloud.githubusercontent.com/assets/303866/26763240/0c0cdea8-4915-11e7-87c7-55d29c8793f2.png">

**Comment by wilsaj** [comment]
It looks like what is happening is:

1. When [the page is being laid out](https://github.com/bpampuch/pdfmake/blob/bad5ccdad56bba7926954552faba8285641064be/src/pageElementWriter.js#L37-L41) and the [image is larger than the available vertical space](https://github.com/bpampuch/pdfmake/blob/86db261d8ba1be2788f5b466ca1ad0ca46bdc889/src/elementWriter.js#L95-L97)
2. Then [a page break is added and placing the image is tried again](https://github.com/bpampuch/pdfmake/blob/bad5ccdad56bba7926954552faba8285641064be/src/pageElementWriter.js#L24-L27)
3. If it still fails because the image too big even for the new blank page, then the image doesn't get placed at all. Instead, it should always force the image placement if working with a blank page.

I can try to put together a PR with a fix for this in the next day or two.

**Comment by liborm85** [comment]
Fixed by PR https://github.com/bpampuch/pdfmake/pull/1031.

**Comment by moumitabala** [comment]
I'm having the same issue. The image I'm creating with dimension **_1140x3190_** but I'm getting only one page pdf with cutting off.  
In my project I'm using pdfmake.min.js directly but as I check here solution is done in a function ElementWriter.prototype.addImage() in /src/elementWriter.js ..

Here is my code ::

```
<script defer src="/js/library/html2canvas.js"></script>
<script defer src="/js/library/pdfmake.min.js"></script>
<script defer src="/js/library/vfs_fonts.js"></script>
```


```
html2canvas(document.getElementById('content_area'), { 
    onrendered: function (canvas) {
        var data = canvas.toDataURL(); 
        
        width = canvas.width;
        height = canvas.height;
                              
        var docDefinition = {                          
            content: [{
                image: data,
                width: width,
                height: height 
            }]
        };                     
        pdfMake.createPdf(docDefinition).download("sample.pdf");
    }                    
});
```

So here how will I implement this solution? So The LARGE image will properly convert into pdf with multiple page.

**Comment by paulmdi** [comment]
i hope this helps: https://gist.github.com/Balkoth/d79a520ca2a3377c15e902ec68790aff

**Comment by jdempcy** [comment]
> i hope this helps: https://gist.github.com/Balkoth/d79a520ca2a3377c15e902ec68790aff

The link does not work. I am running into this issue too - any help is appreciated.
