### ISSUE TITLE
how to put values inside canvas tag?

### ISSUE THREAD

**Issue by Varunprakas** [bpampuch/pdfmake#896]
I am trying add some text in canvas tag, but i didn't see any key there.
This is what i trying to do.
 canvas:[{"text":1,type: 'ellipse',
                                        	x:0 , y: 0, w: 50, h: 50, r1:10,
                                        	"color": "#36a498"}]

**Comment by bautistaaa** [comment]
+1

**Comment by gigglegirl** [comment]
+1

**Comment by bautistaaa** [comment]
i think this may help us. haven't tried it yet though.

https://github.com/bpampuch/pdfmake/pull/793

**Comment by liborm85** [comment]
`canvas` can be used only for draw vectors. 
`relativePosition`, `absolutePosition` can help with writing text to specific position.

**Comment by jelmerjellema** [comment]
I do this to set text above a rectangle. In my code, this rectangle is positioned inside a table cell. 
It feels like a hack, but this seems to work: create a stack, first element is the canvas with the rectangle 

Second element is a 'columns' node with one column. I do this because with a column I can set a width. Using the noWrap:false + maxHeight hack the text gets clipped.

Finally, I set a relativePosition, not on the column, but on the full colums node. Setting a relativePosition on a column does not work: it will stop the sizing of the column.

(sorry for the strange code outline, I typed this in right here...)
```
 let rect = {
    type: 'rect',
     x: 15,
    y: 0, //could be negative to account for padding
    w: 30,
    h: 15,
   color: 'red'
};
//content is the array holding the content definitions
content.push({
 stack: [
  {canvas: [rect]},
  {columns: [
   {
    width: rect.w,
     noWrap: false, //clip at with by wrapping to next line and...
     maxHeight: rect.h, //don't show the wrapped text
     text: 'some text in the rect',
     color: 'white'
    }],
    relativePosition: {
      x: rect.x,
      y: - rect.h
    }
   }
 ]
});
