### ISSUE TITLE
Support JSON Object printing

### ISSUE THREAD

**Issue by Holyphoenix** [bpampuch/pdfmake#980]
I'm utilizing PDFMake on a web applications that uses java on the backend, and use a lot of JSON for calling apis etc.  I'm able to create object representations of objects using the Jackson Library, which makes it easy to convert my objects back and forth.  It would be cool and super useful if PDFMake could support loading a json String to print.

**Comment by liborm85** [comment]
I do not know what is  and what doing Jackson Library. But pdfmake requires docDefinition in JavaScript Object because can contain interactive functions. This functions can not be in JSON text. If you have docDefinition/JSON without functions you can JSON decode to JS object by function `JSON.parse()`.

**Comment by Holyphoenix** [comment]
Awesome, that actually works great.  Thanks!
